import Head from 'next/head'
import Header from '../components/Header'
import Modal from '../components/Modal'
import Newfeeds from '../components/Newfeeds'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen p-0 overflow-y-scroll scrollbar-hide">
      <div>
        <Head>
          <title>Hinstagram2.0</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            href="https://banner2.cleanpng.com/20180407/tvw/kisspng-computer-icons-logo-logo-instagram-5ac88fc4335731.8553791715230934442103.jpg"
          />
        </Head>
        {/* Header */}
        <Header />
        {/* Feed */}
        <Newfeeds />
        {/* Modal */}
        <Modal />
      </div>
    </div>
  )
}
