import Head from 'next/head'
import Header from '../components/Header'
import Newfeeds from '../components/Newfeeds'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="bg-gray-50 h-screen p-0 overflow-y-scroll scrollbar-hide">
      <div>
        <Head>
          <title>Hinstagram2.0</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Header */}
        <Header />
        {/* Feed */}

        {/* Modal */}
        <Newfeeds />
      </div>
    </div>
  )
}
